#!/usr/bin/env python3
# -*- кодировка: utf-8 -*-
import math
import sys


a='рентгеноэлектрокардиография123456789'

print(a)

s,k=map(int, input('Введите позиции s и k (s>k) : ').split())

c=a[s-1]

a=a[:s-1]+a[s:]

a=a[:k-1]+c+a[k-1:]

print(a)
